### ISSUE TITLE
Build errors and Groups Roles Management

### ISSUE THREAD

**Issue by papyr** [naeemafzal/Asp.netIdentity#1]
Hi, this was very nice, a rare video addresses many questions.

Please also help with Group Roles based permission.
Some build errors. Any chance you can update the nugets and checkin, newton soft and OWIN does not work.

I was able to fix some of the errors.

1. In each project=>right click,->properties, select target as 4.7.1 then build.
2. Different versions of newtonsoft & OWIN in different projects (consolidate), so they are all same version.
3. Nuget Restore repair, done.
4. I will try to create a pull request to add a nice theme

thanks

**Comment by naeemafzal** [comment]
Hi @papyr 
Thanks for pointing this out. This is now fixed.

**Issue 1**
Nuget was trying to load missing packages locally.
**Solution**
https://stackoverflow.com/questions/22909506/this-project-references-nuget-packages-that-are-missing-on-this-computer

**Issue 2**
Multiple versions of the nuget packages
**Solution**
Fixed the issue by picking up the latest version out of the two.

**Group Roles**
For group roles please feel free to update the repository.

Thanks

**Comment by papyr** [comment]
Any chance you can show us how to do Groups a sub segment of Roles
